// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDlH7gDHvBwkU3usySEq3OtjfTIFimfoE',
    appId: '1:1085310872535:web:bf9dae5371e136adddb992',
    messagingSenderId: '1085310872535',
    projectId: 'flutter-c4f7a',
    authDomain: 'flutter-c4f7a.firebaseapp.com',
    storageBucket: 'flutter-c4f7a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCykiId_hnzGOK0UxVQFcz87XtO36ljmyc',
    appId: '1:1085310872535:android:40330cabba51dc31ddb992',
    messagingSenderId: '1085310872535',
    projectId: 'flutter-c4f7a',
    storageBucket: 'flutter-c4f7a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPBjYUdRRzYgMLiWDP6aZcWLHrMGPrpz8',
    appId: '1:1085310872535:ios:121b72875fda1c50ddb992',
    messagingSenderId: '1085310872535',
    projectId: 'flutter-c4f7a',
    storageBucket: 'flutter-c4f7a.firebasestorage.app',
    iosBundleId: 'srs.help.srsproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPBjYUdRRzYgMLiWDP6aZcWLHrMGPrpz8',
    appId: '1:1085310872535:ios:121b72875fda1c50ddb992',
    messagingSenderId: '1085310872535',
    projectId: 'flutter-c4f7a',
    storageBucket: 'flutter-c4f7a.firebasestorage.app',
    iosBundleId: 'srs.help.srsproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDlH7gDHvBwkU3usySEq3OtjfTIFimfoE',
    appId: '1:1085310872535:web:a1d6a67bdcfb0007ddb992',
    messagingSenderId: '1085310872535',
    projectId: 'flutter-c4f7a',
    authDomain: 'flutter-c4f7a.firebaseapp.com',
    storageBucket: 'flutter-c4f7a.firebasestorage.app',
  );
}
